name: Manga Scraper Bot

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları İndir
        uses: actions/checkout@v4

      - name: Node.js Kurulumu
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Botu Çalıştır
        run: node scraper.mjs
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
